## ENABLE MOUSE SUPPORT
set -g mouse on
#set -g set-clipboard on

## INCREASE SCROLLBACK
set -g history-limit 10240

## TOGGLE BROADCASTING INPUT WITH Ctrl + b B
bind B setw synchronize-panes
set -g status-left "#{?pane_synchronized,#[bg=red] SYNCHRONIZED ,}"

